site_name: metalicious
pages:
	- ['Introduction': 'index.md']
	- ['Installation': 'installation.md']
	- ['Adding Data': 'adding-data.md']

theme: readthedocs

repo_url: https://github.com/Chicago/metalicious

copyright: Copyright &copy; 2014, <a href="https://cityofchicago.org">City of Chicago</a>. 
google_analytics: ['UA-27795084-5', 'mkdocs.org']